{% set name = "vcpkg" %}
{% set version = "2021.05.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/vcpkg/archive/refs/tags/{{ version }}.tar.gz
  sha256: 907f26a5357c30e255fda9427f1388a39804f607a11fa4c083cc740cb268f5dc

build:
  number: 0

requirements:
  run:
    - vcpkg-tool

test:
  commands:
    - vcpkg --help || true             # [unix]
    - vcpkg.exe --help & exit 0        # [win]
    - vcpkg.exe install nlohmann-json  # [win]
    # - vcpkg install nlohmann-json      # [osx]

about:
  home: https://github.com/microsoft/vcpkg
  license: MIT
  license_file: LICENSE.txt
  summary: https://github.com/microsoft/vcpkg

extra:
  recipe-maintainers:
    - wolfv
