{% set name = "vcpkg" %}
{% set version = "2022.02.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/vcpkg/archive/refs/tags/{{ version }}.tar.gz
  sha256: c99fee39285691f9440f184ad70cc8d49e3add206c9f1a0141392d6db00b0a85

build:
  number: 0

requirements:
  run:
    - vcpkg-tool

test:
  commands:
    - vcpkg --help || true             # [unix]
    - vcpkg.exe --help & exit 0        # [win]
    - vcpkg.exe install nlohmann-json  # [win]
    - test -f $VCPKG_ROOT/.vcpkg-root  # [unix]
    - if not exist %VCPKG_ROOT%\.vcpkg-root (exit 1)  # [win]

about:
  home: https://github.com/microsoft/vcpkg
  license: MIT
  license_file: LICENSE.txt
  summary: https://github.com/microsoft/vcpkg

extra:
  recipe-maintainers:
    - wolfv
